language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update
install:
    - sudo apt-get install libboost-all-dev libhdf5-serial-dev h5utils doxygen

before_script:
    - mkdir build
    - cd build
    - cmake --version
    - cmake ..

script: make && make check
